version: "3"
services:
  redis:
    image: "redis:latest"
    container_name: redis
    expose:
      - 6379
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - /node_modules
      - .:/app
